services:

  server:
    build:
     context: ./server/
     # context: ./server1/
    expose:
      - 8000
    ports:
      - 8000:8000
    init: true

  client:
    build:
      #context: ./client/
      context: ./client2/
    expose:
      - 8001
    ports:
      - 8001:8001
    links:
        - server
    init: true

